import "./globals.css"

import { Analytics } from "@vercel/analytics/react"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className="h-svh flex justify-center items-center p-[16px] sm:p-[44px]">
        <div className="shadow-gray-300 shadow-xl rounded-md p-[20px] sm:p-[40px] backdrop-blur-xl w-full h-full">
          <Analytics />
          {children}
        </div>
      </body>
    </html>
  )
}